# Generated by Django 3.0.4 on 2020-09-08 05:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientea'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pvp',
        ),
        migrations.AddField(
            model_name='product',
            name='cirugias',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cirugias'),
        ),
        migrations.AddField(
            model_name='product',
            name='cirujano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cirujano', to='erp.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='cirujano2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cirujano2', to='erp.Category', verbose_name='Cirujano2'),
        ),
        migrations.AddField(
            model_name='product',
            name='colgajo',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Colgajo'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='duracion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Duracion Cirugia'),
        ),
        migrations.AddField(
            model_name='product',
            name='edad',
            field=models.IntegerField(default=22, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='product',
            name='extrae',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Extrae'),
        ),
        migrations.AddField(
            model_name='product',
            name='finalizacionanestesia',
            field=models.TimeField(blank=True, null=True, verbose_name='Finalizacion Anestesia'),
        ),
        migrations.AddField(
            model_name='product',
            name='finalizacioncirugia',
            field=models.TimeField(blank=True, null=True, verbose_name='Finalizacion Cirugia'),
        ),
        migrations.AddField(
            model_name='product',
            name='identificacion',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Identificacion'),
        ),
        migrations.AddField(
            model_name='product',
            name='inicioanestesia',
            field=models.TimeField(blank=True, null=True, verbose_name='Inicio Anestesia'),
        ),
        migrations.AddField(
            model_name='product',
            name='iniciocirugia',
            field=models.TimeField(blank=True, null=True, verbose_name='Inicio Cirugia'),
        ),
        migrations.AddField(
            model_name='product',
            name='klein',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Klein'),
        ),
        migrations.AddField(
            model_name='product',
            name='md',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MD'),
        ),
        migrations.AddField(
            model_name='product',
            name='mi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MI'),
        ),
        migrations.AddField(
            model_name='product',
            name='observaciones',
            field=models.TextField(blank=True, max_length=999, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='product',
            name='transferencia',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Transferencia'),
        ),
    ]
