# Generated by Django 3.0.4 on 2020-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20200908_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_joined'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientea'},
        ),
        migrations.AddField(
            model_name='product',
            name='colgajo2',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Colgajo I'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colgajo',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Colgajo D'),
        ),
    ]
