# Generated by Django 3.0.4 on 2020-09-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20200908_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bussines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=20, verbose_name='R.U.T / I.D')),
                ('address', models.CharField(max_length=150, verbose_name='Direccion')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('about', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Acerca De Nosotros')),
                ('descripcion', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descripcion')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logob/%Y/%m/%d', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['id'],
            },
        ),
    ]
