# Generated by Django 3.0.4 on 2020-09-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20200916_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='duracion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Duracion Cirugia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='edad',
            field=models.IntegerField(default=0, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extrae',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Extrae'),
        ),
        migrations.AlterField(
            model_name='product',
            name='identificacion',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Identificacion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='klein',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Klein'),
        ),
        migrations.AlterField(
            model_name='product',
            name='md',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MI'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transferencia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Transferencia'),
        ),
    ]
