# Generated by Django 3.0.4 on 2021-04-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20200916_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detsale',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cli',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='DetSale',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
