# Generated by Django 3.0.4 on 2021-08-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20210410_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Hemoglobina'),
        ),
        migrations.AddField(
            model_name='product',
            name='inr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='INR'),
        ),
        migrations.AddField(
            model_name='product',
            name='plaquetas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Plaquetas'),
        ),
    ]
