# Generated by Django 3.0.4 on 2020-09-09 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_bussines'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Bussines', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='cc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cedula'),
        ),
    ]
